[tool.poetry]
name = "sqlmodelrepository"
version = "1.0.0"
description = "sqlmodel repository pattern implementation"
authors = ["Yannic Schröer"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
sqlmodel = "^0.0.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
